title: Ricardo Valeriano [on the interwebz]
tagline: An Average Boring Dev Blog
url: "https://blog.ricardovaleriano.com"
paginate: 1
description: "An Average Boring Dev Blog"

author:
  name: Ricardo Valeriano
  url: https://www.youtube.com/c/FunOnCoding
  twitter: sr_valeriano

gems:
  - jekyll-paginate

markdown: kramdown
