title: Ricardo Valeriano [on the interwebz]
tagline: An Average Boring Dev Blog
baseurl: "https://ricardovaleriano.github.io/blog"
paginate: 1

author:
  name: Ricardo Valeriano
  url: https://www.youtube.com/c/FunOnCoding
  twitter: sr_valeriano

gems:
  - jekyll-paginate

markdown: kramdown
