title: Ricardo Valeriano [aka Mr. Sourcerer]
tagline: Software Development Stuff
url: http://blog.ricardovaleriano.com
paginate: 1
description: Software Development Stuff

author:
  name: Ricardo Valeriano
  url: https://www.youtube.com/c/FunOnCoding
  twitter: mr_sourcerer

gems:
  - jekyll-paginate

highlighter: rouge

markdown: kramdown
