title: Software Dev Shenanigans
tagline: A blog by Ricardo Valeriano [aka Mr. Sourcerer]
url: http://blog.ricardovaleriano.com
paginate: 1
description: Software Development Shenanigans

author:
  name: Ricardo Valeriano
  url: https://github.com/mistersourcerer
  twitter: https://twitter.com/mr_sourcerer
  youtube: https://youtube.com/@mistersourcerer-ptbr

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-tagging-related_posts

highlighter: rouge

markdown: kramdown
