title: Ricardo Valeriano [on the interwebz]
tagline: An Average Boring Dev Blog
baseurl: ""
paginate: 1

author:
  name: Ricardo Valeriano
  url: https://www.youtube.com/c/FunOnCoding
  twitter: sr_valeriano

gems:
  - jekyll-paginate

markdown: kramdown
